version: 0.2
#Paths are relative to project root
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands: 
      - orignpmversion=$(npm -v)
      - echo "original npm version:" $orignpmversion
      - npm i npm@latest -g
      - currentnpmversion=$(npm -v)
      - echo "current npm version:" $currentnpmversion
      - npm install -g jsonlint
      - npm install -g json-dynamo-putrequest
      - npm install -g node-lambda
      - npm install -g typescript
      - npm install -g aws-cdk
      - pip install rdk
  pre_build:
    commands:
      # Setting up build for Lambda NodeJS Functions
      - cd $CODEBUILD_SRC_DIR/
      - chmod +x ./cf/cicd/*.sh
      # Validating CFN Templates
      - echo "Validating Static CF templates"
      # This fancy line compiles all yaml in our project folder excluding the '_template' folder
      - |
        for f in $(find ./cf/project -type d \( -name _template \) -prune -false -o -name '*.yaml' -o -name '*.yml'); do
          echo "Validating CloudFormation template file $f"
          aws cloudformation validate-template --template-body file://$f
        done
  build:
    commands:
      # Create unique Build Guid
      - buildGuid=$(date +"%Y%m%d%H%S")
      - echo -n "$buildGuid" > buildguid.txt
      - pwd
      - cd $CODEBUILD_SRC_DIR/
      - pwd
      # Build DynamoDB configuration data/update
      - ./cf/cicd/build_dynamo.sh -r $PROJECT_PREFIX
      # Package Lambdas as ZIP
      - ./cf/cicd/build_lambdas.sh
      # Build Typescript AWS CDK
      - ./cf/cicd/build_ts_aws_cdk.sh -b $buildGuid -r $PROJECT_PREFIX -a $CURRENT_AWS_ACCOUNT_ID
      # Build AWS Config RDK
      - ./cf/cicd/build_rdk.sh -s $RDK_RULES_S3_BUCKET -l $RDK_LAMBDA_ROLE -e $ENVIRONMENT_TYPE
      # Copy stacks to S3
      - echo "Copy Static CF Stack Templates to S3"
      - |
        for cf_template in $(find ./cf/project -type d \( -name _template \) -prune -false -o -name '*.yaml' -o -name '*.yml'); do
          templateName="$(echo $cf_template | rev | cut -d'/' -f 1 | rev)"
          echo "$templateName"
          aws cloudformation package --template-file $cf_template --output-template-file $templateName --s3-bucket $CODEPIPELINE_BUCKET --kms-key-id $KMS_KEY_ARN
          aws s3 cp "$templateName" "s3://$CODEPIPELINE_BUCKET/$buildGuid/$templateName" --sse aws:kms --sse-kms-key-id $KMS_KEY_ARN
        done
      - echo "Copy CDK Generated CF Stack Templates to S3"
      - |
        for cf_template in $(find ./.build/cdk -type d \( -name _template \) -prune -false -o -name '*.template.json'); do
          templateName="$(echo $cf_template | rev | cut -d'/' -f 1 | rev)"
          echo "$templateName"
          aws cloudformation package --template-file $cf_template --output-template-file $templateName --s3-bucket $CODEPIPELINE_BUCKET --kms-key-id $KMS_KEY_ARN
          aws s3 cp "$templateName" "s3://$CODEPIPELINE_BUCKET/$buildGuid/$templateName" --sse aws:kms --sse-kms-key-id $KMS_KEY_ARN
        done
      # Update Rule Template to Artifact S3 Bucket
      - echo "Copy RDK Generated CF Stack Templates to S3"
      - |
        for cf_template in $(find ./.build/rdk -type d \( -name _template \) -prune -false -o -name '*.template.json'); do
          templateName="$(echo $cf_template | rev | cut -d'/' -f 1 | rev)"
          echo "$templateName"
          aws s3 cp "$cf_template" "s3://$CODEPIPELINE_BUCKET/$buildGuid/$templateName" --sse aws:kms --sse-kms-key-id $KMS_KEY_ARN
        done
artifacts:
  files:
    - ./MasterStack-*.template.json
    - ./buildguid.txt
