AWSTemplateFormatVersion: '2010-09-09'
Description: Master stack which references all project CloudFormation outputs

Parameters:
  #Application Generic Parameters >>
  BuidGuid:
    Type: String
    Description: Unique Id used in build to force CloudFormation StackSet to update
  ProjectFriendlyName:
    Type: String
    Description: Enter an friendly project name for Tagging
  ProjectResourcePrefix:
    Type: String
    Description: Enter a unique prefix for the project resources.
  EnvironmentType:
    Type: String
    AllowedValues:
      - prod
      - test
    Description: Enter destination environment type
  #<< Application Generic Parameters
  
  #StackSet Deployment Settings >>
  # >> Default Settings
  DefaultDeploymentOrgUnitIds:
    Type: String
    Description: Comma separated string of OrganizationalUnitIds to deploy stackset to
  DefaultDeploymentRegions:
    Type: String
    Description: Comma separated string of AWS Regions to deploy stackset to
  DefaultRetainStacksOnAccountRemoval:
    Type: String
    Description: Friendly environment name of project
  # << Default Settings
  # >> StackSet-Specific Settings (Add as necessary)
  StackSetS3ExampleDeploymentOrgUnitIds:
    Type: String
    Description: Comma separated string of OrganizationalUnitIds to deploy stackset to
  StackSetS3ExampleDeploymentRegions:
    Type: String
    Description: Comma separated string of AWS Regions to deploy stackset to
  StackSetS3ExampleRetainStacksOnAccountRemoval:
    Type: String
    Description: Friendly environment name of project
  StackSetVPCDeploymentOrgUnitIds:
    Type: String
    Description: Comma separated string of OrganizationalUnitIds to deploy stackset to
  StackSetVPCDeploymentRegions:
    Type: String
    Description: Comma separated string of AWS Regions to deploy stackset to
  StackSetVPCRetainStacksOnAccountRemoval:
    Type: String
    Description: Friendly environment name of project
  # << StackSet-Specific Settings 
  #<< StackSet Deployment Settings

  #Stack-Specific Parameters >>
  # VPC Endpoints>>
  VPCEndpointType:
    Type: String
    Default: 'Interface'
    Description: Specifies VPC Endpoint type
    AllowedValues:
      - 'Interface'
      - 'Gateway'
  VPCEndpointPrivateDnsEnabled:
    Type: String
    Default: 'true'
    Description: Indicate whether Private DNS is enabled
    AllowedValues:
      - 'true'
      - 'false'
  # << VPC Endpoints
  #<< Project Specific Parameters

Mappings: 
  EnvironmentFriendlyName: 
    prod: 
      Name: Production Stack
    test: 
      Name: Test Stack

Resources:
  SampleStackSetS3:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TimeoutInMinutes: '30'
      TemplateURL:
        !Sub "https://${ProjectResourcePrefix}-main-artifacts-codebuild.s3.amazonaws.com/${BuidGuid}/S3StackSet_output.yaml"
      Parameters:
        BuidGuid:
          Ref: BuidGuid
        EnvironmentType:
          Ref: EnvironmentType
        EnvironmentFriendlyName:
          !FindInMap [EnvironmentFriendlyName, !Ref EnvironmentType, Name]
        ProjectResourcePrefix:
          Ref: ProjectResourcePrefix
        ProjectFriendlyName:
          Ref: ProjectFriendlyName
        OrganizationalUnitIds:
          Ref: StackSetS3ExampleDeploymentOrgUnitIds
        DeploymentRegions:
          Ref: StackSetS3ExampleDeploymentRegions
        RetainStacksOnAccountRemoval:
          Ref: StackSetS3ExampleRetainStacksOnAccountRemoval
      Tags:
        - Key: Name
          Value: SampleStackSet
        - Key: Project
          Value: !Ref ProjectFriendlyName
        - Key: Purpose
          Value: Test StackSet
        - Key: Environment
          Value: 
            !FindInMap [EnvironmentFriendlyName, !Ref EnvironmentType, Name]
