AWSTemplateFormatVersion: '2010-09-09'
Description: DevSecOps Stackset for the DevSecOps Project

Parameters:
  #Application Generic Parameters
  BuildGuid:
    Type: String
    Description: Unique Id used in build to force CloudFormation StackSet to update
  ProjectFriendlyName:
    Type: String
    Description: Enter an friendly project name for Tagging
  ProjectResourcePrefix:
    Type: String
    Description: Enter a unique prefix for the project resources.
  EnvironmentType:
    Type: String
    AllowedValues:
      - prod
      - test
    Description: Enter destination environment type 
  EnvironmentFriendlyName:
    Type: String
    Description: Friendly environment name of project
  OrganizationalUnitIds:
    Type: String
    Description: Comma separated string of OrganizationalUnitIds to deploy stackset to
  DeploymentRegions:
    Type: String
    Description: Comma separated string of AWS Regions to deploy stackset to
  RetainStacksOnAccountRemoval:
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Description: Friendly environment name of project
  #Project Specific Parameters >>
  
  #<< Project Specific Parameters
    

Resources:
  XStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties: 
      StackSetName: !Sub "${ProjectResourcePrefix}-s3stackset-${EnvironmentType}"
      TemplateURL: !Sub "https://${ProjectResourcePrefix}-main-artifacts-codebuild.s3.amazonaws.com/${BuildGuid}/XStack_output.yaml"
      AutoDeployment: 
        Enabled: true
        RetainStacksOnAccountRemoval: !Ref RetainStacksOnAccountRemoval
      Capabilities: 
        - 'CAPABILITY_IAM'
        - 'CAPABILITY_NAMED_IAM'
      Description: !Sub "Stack set for project ${ProjectResourcePrefix}"
      Parameters: 
        - ParameterKey: ProjectFriendlyName
          ParameterValue: !Ref ProjectFriendlyName
        - ParameterKey: ProjectResourcePrefix
          ParameterValue: !Ref ProjectResourcePrefix
        - ParameterKey: EnvironmentType
          ParameterValue: !Ref EnvironmentType
        - ParameterKey: EnvironmentFriendlyName
          ParameterValue: !Ref EnvironmentFriendlyName
      PermissionModel: SERVICE_MANAGED
      StackInstancesGroup: 
        - DeploymentTargets:
            OrganizationalUnitIds: 
              !Split [",", !Ref OrganizationalUnitIds]
          Regions: !Split [",", !Ref DeploymentRegions]
      Tags:
        - Key: Project
          Value: !Ref ProjectFriendlyName
        - Key: Purpose
          Value: DevSecOps StackSet
        - Key: Environment
          Value: 
            !Ref EnvironmentFriendlyName
