AWSTemplateFormatVersion: "2010-09-09"
Description: "Enable service specific VPC Endpoints"

Parameters:
  ProjectFriendlyName:
    Type: String
    Description: Enter an friendly project name for Tagging
  ProjectResourcePrefix:
    Type: String
    Description: Enter a unique prefix for the project resources.
  EnvironmentType:
    Type: String
    AllowedValues:
      - prod
      - test
    Description: Enter destination environment type
  EnvironmentFriendlyName:
    Type: String
    Description: Friendly environment name of project
  VPCEndpointType:
    Type: String
    Default: 'Interface'
    Description: Specifies VPC Endpoint type
    AllowedValues:
      - 'Interface'
      - 'Gateway'
  VPCEndpointPrivateDnsEnabled:
    Type: String
    Default: 'true'
    Description: Indicates whether Private DNS is enabled
    AllowedValues:
      - 'true'
      - 'false'

Resources:
    DMSEndpoint:
        Type: "AWS::EC2::VPCEndpoint"
        Properties:
            ServiceName: "com.amazonaws.ap-southeast-2.dms"
            VpcEndpointType: !Ref VPCEndpointType
            VpcId: 
              Fn::ImportValue: 'LZ-VPC-Id'
            SubnetIds: 
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet1AID'
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet2AID'
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet3AID'
            PrivateDnsEnabled: !Ref VPCEndpointPrivateDnsEnabled
            SecurityGroupIds: 
              - Fn::ImportValue: 'LZ-VPC-Default-SecurityGroup'

    KinesisStreamEndpoint:
        Type: "AWS::EC2::VPCEndpoint"
        Properties:
            ServiceName: "com.amazonaws.ap-southeast-2.kinesis-streams"
            VpcEndpointType: !Ref VPCEndpointType
            VpcId: 
              Fn::ImportValue: 'LZ-VPC-Id'
            SubnetIds: 
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet1AID'
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet2AID'
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet3AID'
            PrivateDnsEnabled: !Ref VPCEndpointPrivateDnsEnabled
            SecurityGroupIds: 
              - Fn::ImportValue: 'LZ-VPC-Default-SecurityGroup'

    KMSEndpoint:
        Type: "AWS::EC2::VPCEndpoint"
        Properties:
            ServiceName: "com.amazonaws.ap-southeast-2.kms"
            VpcEndpointType: !Ref VPCEndpointType
            VpcId: 
              Fn::ImportValue: 'LZ-VPC-Id'
            SubnetIds: 
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet1AID'
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet2AID'
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet3AID'
            PrivateDnsEnabled: !Ref VPCEndpointPrivateDnsEnabled
            SecurityGroupIds: 
              - Fn::ImportValue: 'LZ-VPC-Default-SecurityGroup'

    SSMEndpoint:
        Type: "AWS::EC2::VPCEndpoint"
        Properties:
            ServiceName: "com.amazonaws.ap-southeast-2.ssm"
            VpcEndpointType: !Ref VPCEndpointType
            VpcId: 
              Fn::ImportValue: 'LZ-VPC-Id'
            SubnetIds: 
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet1AID'
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet2AID'
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet3AID'
            PrivateDnsEnabled: !Ref VPCEndpointPrivateDnsEnabled
            SecurityGroupIds: 
              - Fn::ImportValue: 'LZ-VPC-Default-SecurityGroup'

    GlueEndpoint:
        Type: "AWS::EC2::VPCEndpoint"
        Properties:
            ServiceName: "com.amazonaws.ap-southeast-2.glue"
            VpcEndpointType: !Ref VPCEndpointType
            VpcId:
              Fn::ImportValue: 'LZ-VPC-Id'
            SubnetIds: 
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet1AID'
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet2AID'
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet3AID'
            PrivateDnsEnabled: !Ref VPCEndpointPrivateDnsEnabled
            SecurityGroupIds: 
              - Fn::ImportValue: 'LZ-VPC-Default-SecurityGroup'

    RedshiftEndpoint:
        Type: "AWS::EC2::VPCEndpoint"
        Properties:
            ServiceName: "com.amazonaws.ap-southeast-2.redshift"
            VpcEndpointType: !Ref VPCEndpointType
            VpcId:
              Fn::ImportValue: 'LZ-VPC-Id'
            SubnetIds: 
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet1AID'
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet2AID'
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet3AID'
            PrivateDnsEnabled: !Ref VPCEndpointPrivateDnsEnabled
            SecurityGroupIds: 
              - Fn::ImportValue: 'LZ-VPC-Default-SecurityGroup'

    RDSEndpoint:
        Type: "AWS::EC2::VPCEndpoint"
        Properties:
            ServiceName: "com.amazonaws.ap-southeast-2.rds"
            VpcEndpointType: !Ref VPCEndpointType
            VpcId:
              Fn::ImportValue: 'LZ-VPC-Id'
            SubnetIds: 
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet1AID'
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet2AID'
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet3AID'
            PrivateDnsEnabled: !Ref VPCEndpointPrivateDnsEnabled
            SecurityGroupIds: 
              - Fn::ImportValue: 'LZ-VPC-Default-SecurityGroup'

    SQSEndpoint:
        Type: "AWS::EC2::VPCEndpoint"
        Properties:
            ServiceName: "com.amazonaws.ap-southeast-2.sqs"
            VpcEndpointType: !Ref VPCEndpointType
            VpcId:
              Fn::ImportValue: 'LZ-VPC-Id'
            SubnetIds: 
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet1AID'
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet2AID'
              - Fn::ImportValue: 'LZ-VPC-PrivateSubnet3AID'
            PrivateDnsEnabled: !Ref VPCEndpointPrivateDnsEnabled
            SecurityGroupIds: 
              - Fn::ImportValue: 'LZ-VPC-Default-SecurityGroup'